Add ASR calculator
d61h6k4/call-assistant-bot pull request #40
Opened 2024-08-07 14:46 UTC by Demontego

Add ASR calculator and tests

Introduced a new ASR calculator with dependencies to facilitate automatic speech recognition features. Added corresponding ASR calculator tests including necessary data and dependencies to ensure functionality and reliability. This enhancement improves speech processing capabilities within the project.
```

2024-08-08 09:58 UTC, d61h6k4 requested changes

2024-08-08 09:58 UTC, d61h6k4 commented on av_transducer/calculators/asr_calculator.cc
> +    static constexpr mediapipe::api2::SideInput<int> kInBufferDurationSec{
You can make it optional by marking like this:
`static constexpr mediapipe::api2::SideInput<int>::optional kInBufferDurationSec`

2024-08-08 09:58 UTC, d61h6k4 commented on av_transducer/calculators/asr_calculator.cc
> +    if (cc->InputSidePackets().HasTag(kInBufferDurationSec.Tag())) {
Note: Mediapipe has a new api now, where we can use fanier version to check that stream is connected.
Here is example: https://github.com/d61h6k4/call-assistant-bot/blob/main/av_transducer/calculators/ffmpeg_sink_video_calculator.cc#L97

2024-08-09 19:17 UTC, Demontego commented on av_transducer/calculators/asr_calculator.cc
> +        auto result = model_->operator()(audio_buffer_);
Here AppendAudioData change old part audio_buffer_. Why??

2024-08-10 09:05 UTC, d61h6k4 approved these changes

2024-08-10 09:07 UTC, merged